
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:12.16
    steps:
       - checkout
       - run:
          name: Install Cypress
          command: npm install cypress
       - run:
          name: Run cypress
          command: npm run cypress
